### PR TITLE
Fixing RVM GPG issues and CI build

### PR DESCRIPTION
**Pull request by zealot128**

### CODE REVIEW

**Comment by zealot128** [comment]
@arBmind any objections? Made some restructuring of key checking.
Not sure about the last part with importing via url. I think that wouldn't work good anyways, as there must be another key downloaded here, too.

**Comment by zealot128** [comment]
Fixes #83

**Comment by arBmind** [comment]
@zealot128 Thank you! Good work.

As long as it works to check the core now, I'm more than happy.

**Comment by arBmind** [comment]
@zealot128 Please change the PR title when this is ready to merge. I see no objections right now.

**Comment by zealot128** [comment]
Great, i rebase my other PRs

**Pull request merged**
