### PR TITLE
README: Fixed the links to the subroles

### PR DESCRIPTION
**Pull request by zealot128**
The links from the main README to the subroles didn't work like that. I've added the missing `tree/develop` to each (might also be tree/master?)

### CODE REVIEW

**Comment by arBmind** [comment]
needs rebase...

**Comment by zealot128** [comment]
done!

**Comment by arBmind** [comment]
Thanks for your fast response.

**Comment by tnt** [comment]
We discussed that [here](https://github.com/dresden-weekly/ansible-rails/pull/5#discussion-diff-27929201) where you suggested to make them absolute for also working from ansible-galaxy. 

I could swear that they had worked...

**Comment by zealot128** [comment]
they didn't - 404 page, needs to be /tree/master oder /tree/develop somewhere.

**Pull request merged**
